import type { Anime, Movie } from '@/types';

// ═══════════════════════════════════════════════════════════════════
// ANIME CATALOG — 17 most popular anime in the Arab world
// Poster images use Pexels stock photos as placeholders.
// Replace `poster` and `banner` URLs with official anime artwork.
// ═══════════════════════════════════════════════════════════════════

export const animeList: Anime[] = [
  {
    id: 'conan',
    malId: 235,
    title: 'Detective Conan',
    titleAr: 'المحقق كونان',
    poster: '',
    banner: '',
    rating: 9.2,
    year: '1996 - مستمر',
    genres: ['غموض', 'أكشن', 'مغامرة'],
    studio: 'TMS Entertainment',
    status: 'مستمر',
    synopsis: 'المحقق الشاب شينيتشي كودو يتحول إلى طفل بسبب دواء غامض تطلقه منظمة الجريمة ذات الرداء الأسود. يتخذ اسم كونان إيدوغاوا ويواصل حل أصعب القضايا بينما يبحث عن طريقة لاستعادة جسده الأصلي.',
    episodeCount: 1130,
    trending: true,
  },
  {
    id: 'onepiece',
    malId: 21,
    title: 'One Piece',
    titleAr: 'ون بيس',
    poster: '',
    banner: '',
    rating: 9.5,
    year: '1999 - مستمر',
    genres: ['مغامرة', 'أكشن', 'كوميدي'],
    studio: 'Toei Animation',
    status: 'مستمر',
    synopsis: 'مونكي دي لوفي وطاقم قراصنة قبعة القش يبحرون عبر العالم بحثاً عن الكنز الأسطوري ون بيس ليصبح لوفي ملك القراصنة التالي.',
    episodeCount: 1110,
  },
  {
    id: 'aot',
    malId: 16498,
    title: 'Attack on Titan',
    titleAr: 'هجوم العمالقة',
    poster: '',
    banner: '',
    rating: 9.4,
    year: '2013 - 2023',
    genres: ['أكشن', 'دراما', 'غموض'],
    studio: 'WIT Studio / MAPPA',
    status: 'منتهي',
    synopsis: 'بعد قرن من اختباء البشرية داخل أسوار ضخمة لحمايتها من العمالقة آكلة لحوم البشر، يقرر إيرين ييغر وأصدقاؤه الانضمام لفيلق الاستطلاع ومحاربة العمالقة لكشف سر أصولهم.',
    episodeCount: 89,
  },
  {
    id: 'demonslayer',
    malId: 38000,
    title: 'Demon Slayer',
    titleAr: 'قاتل الشياطين',
    poster: '',
    banner: '',
    rating: 9.0,
    year: '2019 - مستمر',
    genres: ['أكشن', 'خارق', 'تاريخي'],
    studio: 'ufotable',
    status: 'مستمر',
    synopsis: 'بعد مذبحة عائلته على يد الشياطين وتحول أخته نيزوكو إلى شيطان، ينضم تانجيرو كامادو إلى فيلق قتلة الشياطين في رحلة لاستعادة إنسانية أخته والانتقام من الملك موزان.',
    episodeCount: 63,
  },
  {
    id: 'jjk',
    malId: 40748,
    title: 'Jujutsu Kaisen',
    titleAr: 'جوجوتسو كايسن',
    poster: '',
    banner: '',
    rating: 8.9,
    year: '2020 - مستمر',
    genres: ['أكشن', 'خارق', 'غموض'],
    studio: 'MAPPA',
    status: 'مستمر',
    synopsis: 'يوجي إيتادوري طالب عادي يبتلع إصبع ساتورو غوجو الملعون ليصبح وعاءً للقوة الملعونة. ينضم لمدرسة جوجوتسو الثانوية ليتعلم السحر ويتعقب باقي الأصابع.',
    episodeCount: 47,
  },
  {
    id: 'naruto',
    malId: 1735,
    title: 'Naruto Shippuden',
    titleAr: 'ناروتو شيبودن',
    poster: '',
    banner: '',
    rating: 8.7,
    year: '2007 - 2017',
    genres: ['أكشن', 'مغامرة', 'شونين'],
    studio: 'Pierrot',
    status: 'منتهي',
    synopsis: 'يعود ناروتو أوزوماكي بعد سنوات من التدريب ليواجه منظمة الأكاتسكي الشريرة التي تسعى للسيطرة على جميع وحوش البيجو، بينما يكافح لتحقيق حلمه بأن يصبح الهوكاجي.',
    episodeCount: 500,
  },
  {
    id: 'hxh',
    malId: 11061,
    title: 'Hunter x Hunter',
    titleAr: 'القناص',
    poster: '',
    banner: '',
    rating: 9.1,
    year: '2011 - 2014',
    genres: ['مغامرة', 'أكشن', 'خيال'],
    studio: 'Madhouse',
    status: 'منتهي',
    synopsis: 'غون فريكس يبدأ رحلة للعثور على والده الذي تركه صغيراً. يلتقي بمجموعة من الأصدقاء ويخضع لاختبارات صعبة ليصبح صياداً محترفاً.',
    episodeCount: 148,
  },
  {
    id: 'bluelock',
    malId: 47538,
    title: 'Blue Lock',
    titleAr: 'بلو لوك',
    poster: '',
    banner: '',
    rating: 8.5,
    year: '2022 - مستمر',
    genres: ['رياضي', 'دراما', 'شونين'],
    studio: 'Eight Bit',
    status: 'مستمر',
    synopsis: 'بعد خسارة اليابان في كأس العالم، يطلق مشروع بلو لوك لصناعة أعظم مهاجم كرة قدم في العالم. يويشي إيساغي يجب أن يتفوق على 299 مهاجماً في سجن كرة القدم.',
    episodeCount: 24,
  },
  {
    id: 'deathnote',
    malId: 1535,
    title: 'Death Note',
    titleAr: 'مذكرة الموت',
    poster: '',
    banner: '',
    rating: 9.0,
    year: '2006 - 2007',
    genres: ['غموض', 'نفسي', 'دراما'],
    studio: 'Madhouse',
    status: 'منتهي',
    synopsis: 'لايت ياغامي طالب ثانوي موهوب يعثر على مذكرة خارقة تقتل أي شخص يُكتب اسمه فيها. يقرر خلق عالم خالٍ من الجريمة، لكن العبقري إل يطارد خطاه.',
    episodeCount: 37,
  },
  {
    id: 'opm',
    malId: 30276,
    title: 'One Punch Man',
    titleAr: 'رجل اللكمة الواحدة',
    poster: '',
    banner: '',
    rating: 8.8,
    year: '2015 - مستمر',
    genres: ['أكشن', 'كوميدي', 'خارق'],
    studio: 'Madhouse / J.C.Staff',
    status: 'مستمر',
    synopsis: 'سايتاما بطل قوي لدرجة أنه يهزم أي خصم بلكمة واحدة. يبحث عن خصم يستطيع إثارته بينما يواجه الوحوش والأشرار الذين يهددون الأرض.',
    episodeCount: 24,
  },
  {
    id: 'mha',
    malId: 31964,
    title: 'My Hero Academia',
    titleAr: 'أكاديميتي للأبطال',
    poster: '',
    banner: '',
    rating: 8.4,
    year: '2016 - مستمر',
    genres: ['أكشن', 'مغامرة', 'مدرسي'],
    studio: 'Bones',
    status: 'مستمر',
    synopsis: 'في عالم يمتلك فيه 80% من البشر قوى خارقة، يحلم إيزوكي ميدوريا الذي وُلد بلا قوة بأن يصبح بطلاً. يكتسب قوة الأسطورة أول مايت ويلتحق بأكاديمية الأبطال.',
    episodeCount: 138,
  },
  {
    id: 'berserk',
    malId: 33,
    title: 'Berserk',
    titleAr: 'بيرسيرك',
    poster: '',
    banner: '',
    rating: 8.6,
    year: '1997',
    genres: ['أكشن', 'خيال مظلم', 'دراما'],
    studio: 'OLM',
    status: 'منتهي',
    synopsis: 'غاتس محارب مرتزق يحمل سيفاً ضخماً يطارد مصيره في عالم ساحر ومظلم، باحثاً عن الانتقام من صديقه السابق غريفيث الذي خانه.',
    episodeCount: 25,
  },
  {
    id: 'tokyo',
    malId: 22319,
    title: 'Tokyo Ghoul',
    titleAr: 'غول طوكيو',
    poster: '',
    banner: '',
    rating: 7.9,
    year: '2014 - 2018',
    genres: ['أكشن', 'رعب', 'نفسي'],
    studio: 'Pierrot',
    status: 'منتهي',
    synopsis: 'بعد عملية زرع أعضاء تحول كين كانيكي إلى نصف غول، يجب أن يتكيف مع حياته الجديدة بين البشر والغيلان بينما يقاتل من أجل البقاء في طوكيو.',
    episodeCount: 48,
  },
  {
    id: 'codegeass',
    malId: 1575,
    title: 'Code Geass',
    titleAr: 'كود غياس',
    poster: '',
    banner: '',
    rating: 8.9,
    year: '2006 - 2008',
    genres: ['أكشن', 'ميكا', 'نفسي'],
    studio: 'Sunrise',
    status: 'منتهي',
    synopsis: 'لولوش لامبروج يحصل على قوة غياس التي تجبر أي شخص على طاعته. يستخدمها لقيادة تمرد ضد الإمبراطورية البريطانية المقدسة التي احتلت اليابان.',
    episodeCount: 50,
  },
  {
    id: 'fma',
    malId: 5114,
    title: 'Fullmetal Alchemist: Brotherhood',
    titleAr: 'الكيميائي الفولاذي',
    poster: '',
    banner: '',
    rating: 9.2,
    year: '2009 - 2010',
    genres: ['مغامرة', 'أكشن', 'خيال'],
    studio: 'Bones',
    status: 'منتهي',
    synopsis: 'الأخوان إدوارد وألفونس إلريك يحاولان استعادة أجسادهما بعد فشل تجربة محرمة. يبحثان عن حجر الفيلسوف بينما يكشفان مؤامرة عسكرية مظلمة.',
    episodeCount: 64,
  },
  {
    id: 'monster',
    malId: 19,
    title: 'Monster',
    titleAr: 'مونستر',
    poster: '',
    banner: '',
    rating: 8.8,
    year: '2004 - 2005',
    genres: ['غموض', 'دراما', 'نفسي'],
    studio: 'Madhouse',
    status: 'منتهي',
    synopsis: 'د. كينزو تينما جراح موهوب ينقذ حياة صبي يكبر ليصبح قاتلاً متسلسلاً مروعاً. يبدأ تينما رحلة مطاردة عبر أوروبا لتصحيح خطئه.',
    episodeCount: 74,
  },
  {
    id: 'vinland',
    malId: 37521,
    title: 'Vinland Saga',
    titleAr: 'ملحمة فاينلاند',
    poster: '',
    banner: '',
    rating: 8.8,
    year: '2019 - مستمر',
    genres: ['أكشن', 'تاريخي', 'دراما'],
    studio: 'WIT Studio / MAPPA',
    status: 'مستمر',
    synopsis: 'تورفين شاب يبحث عن الانتقام من القائد الذي قتل أباه. رحلته تأخعه عبر حروب الفايكنج إلى أرض جديدة تدعى فاينلاند.',
    episodeCount: 48,
  },
];

// ═══════════════════════════════════════════════════════════════════
// MOVIES — grouped by anime (each anime has its own films)
// ═══════════════════════════════════════════════════════════════════

export const movieList: Movie[] = [
  // ─── أفلام المحقق كونان (26 فيلماً) ───
  { id: 'conan-movie-1', animeId: 'conan', malId: 2347, title: 'Detective Conan Movie 1', titleAr: 'كونان: عداد الساعة 5', poster: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.0, year: '1997', duration: '95 دقيقة', genres: ['غموض', 'أكشن'], synopsis: 'سلسلة تفجيرات تحدث في طوكيو، كونان يجب أن يكتشف هوية المجرم قبل أن تنفجر القنبلة الأخيرة.' },
  { id: 'conan-movie-2', animeId: 'conan', title: 'Detective Conan Movie 2', titleAr: 'كونان: الهدف الرابع عشر', poster: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.1, year: '1998', duration: '100 دقيقة', genres: ['غموض', 'أكشن'], synopsis: 'مجموعة من الأصدقاء يتلقون دعوات غامضة، ويجد كونان نفسه في سباق مع الوقت لإنقاذهم.' },
  { id: 'conan-movie-3', animeId: 'conan', title: 'Detective Conan Movie 3', titleAr: 'كونان: ساحر القرن الأخير', poster: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.2, year: '1999', duration: '99 دقيقة', genres: ['غموض', 'أكشن'], synopsis: 'مسرحية سحرية تتحول إلى جريمة حقيقية، وكونان يجب أن يكشف الخدعة القاتلة.' },
  { id: 'conan-movie-4', animeId: 'conan', title: 'Detective Conan Movie 4', titleAr: 'كونان: قاتل في عيون داكنة', poster: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.0, year: '2000', duration: '99 دقيقة', genres: ['غموض', 'أكشن'], synopsis: 'سلسلة جرائم قتل ترتبط بضحايا فقدوا بصرهم، كونان يبحث عن الصلة المشتركة.' },
  { id: 'conan-movie-5', animeId: 'conan', title: 'Detective Conan Movie 5', titleAr: 'كونان: العد التنازلي للسماء', poster: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.3, year: '2001', duration: '99 دقيقة', genres: ['غموض', 'أكشن'], synopsis: 'مبنى شاهق يتحول إلى فخ مميت، وكونان يجب أن يفك الشفرة قبل الانفجار.' },
  { id: 'conan-movie-6', animeId: 'conan', title: 'Detective Conan Movie 6', titleAr: 'كونان: شبح شارع بيكر', poster: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.4, year: '2002', duration: '107 دقيقة', genres: ['غموض', 'أكشن'], synopsis: 'لعبة واقع افتراضي تتحول إلى كابوس حقيقي، وكونان يحاول الخروج قبل فوات الأوان.' },
  { id: 'conan-movie-7', animeId: 'conan', title: 'Detective Conan Movie 7', titleAr: 'كونان: تقاطع الطرق في المخبأ', poster: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.1, year: '2003', duration: '107 دقيقة', genres: ['غموض', 'أكشن'], synopsis: 'سرقة مجوهرات وجرائم قتل متصلة، كونان يطارد المجرم في أنحاء المدينة.' },
  { id: 'conan-movie-8', animeId: 'conan', title: 'Detective Conan Movie 8', titleAr: 'كونان: ساحر السماء الفضية', poster: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.2, year: '2004', duration: '107 دقيقة', genres: ['غموض', 'أكشن'], synopsis: 'مغنية أوبرا مشهورة تصبح هدف قاتل غامض، وكونان يحميها بينما يكشف الحقيقة.' },
  { id: 'conan-movie-9', animeId: 'conan', title: 'Detective Conan Movie 9', titleAr: 'كونان: استراتيجية ما فوق المياه', poster: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.0, year: '2005', duration: '109 دقيقة', genres: ['غموض', 'أكشن'], synopsis: 'جريمة على متن سفينة سياحية، كونان يجب أن يحل اللغز وسط الأمواج العاتية.' },
  { id: 'conan-movie-10', animeId: 'conan', title: 'Detective Conan Movie 10', titleAr: 'كونان: لحن وداع المحقق', poster: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.3, year: '2006', duration: '111 دقيقة', genres: ['غموض', 'أكشن'], synopsis: 'محققون يتجمعون في منتجع، لكن واحداً منهم يصبح الهدف التالي.' },
  { id: 'conan-movie-11', animeId: 'conan', title: 'Detective Conan Movie 11', titleAr: 'كونان: علم القراصنة في المحيط الأزرق', poster: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.1, year: '2007', duration: '107 دقيقة', genres: ['غموض', 'أكشن'], synopsis: 'كنز القراصنة ومقتل غامض يقود كونان في مغامرة بحرية محفوفة بالمخاطر.' },
  { id: 'conan-movie-12', animeId: 'conan', title: 'Detective Conan Movie 12', titleAr: 'كونان: سجل الخوف الكامل', poster: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.2, year: '2008', duration: '115 دقيقة', genres: ['غموض', 'أكشن'], synopsis: 'مدينة تتحرك وفق لغة الجريمة، كونان يحل الشفرة لإنقاذ آلاف الأرواح.' },
  { id: 'conan-movie-13', animeId: 'conan', title: 'Detective Conan Movie 13', titleAr: 'كونان: المطارد الأسود', poster: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.4, year: '2009', duration: '111 دقيقة', genres: ['غموض', 'أكشن'], synopsis: 'منظمة الرداء الأسود تستهدف شهوداً، وكونان يخوض معركة مباشرة ضدهم.' },
  { id: 'conan-movie-14', animeId: 'conan', title: 'Detective Conan Movie 14', titleAr: 'كونان: السفينة الضائعة في السماء', poster: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.0, year: '2010', duration: '109 دقيقة', genres: ['غموض', 'أكشن'], synopsis: 'اختبار طيران لطائرة جديدة يتحول إلى كارثة جوية، وكونان يجب أن يهبط بها بسلام.' },
  { id: 'conan-movie-15', animeId: 'conan', title: 'Detective Conan Movie 15', titleAr: 'كونان: 15 دقيقة من الصمت', poster: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.2, year: '2011', duration: '109 دقيقة', genres: ['غموض', 'أكشن'], synopsis: 'انفجار في برج توكيو، وكونان لديه 15 دقيقة فقط لإنقاذ المدينة.' },
  { id: 'conan-movie-16', animeId: 'conan', title: 'Detective Conan Movie 16', titleAr: 'كونان: الجاسوس الحادي عشر', poster: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.3, year: '2012', duration: '110 دقيقة', genres: ['غموض', 'أكشن'], synopsis: 'جاسوس يختبئ بين ركاب طائرة، وكونان يكشف هويته في أجواء مشحونة بالتوتر.' },
  { id: 'conan-movie-17', animeId: 'conan', title: 'Detective Conan Movie 17', titleAr: 'كونان: المبحر التجاري الخاص', poster: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.1, year: '2013', duration: '110 دقيقة', genres: ['غموض', 'أكشن'], synopsis: 'يخت فاخر، جريمة معقدة، وكونان يبحر نحو الحقيقة.' },
  { id: 'conan-movie-18', animeId: 'conan', title: 'Detective Conan Movie 18', titleAr: 'كونان: بُعد القناص', poster: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.5, year: '2014', duration: '112 دقيقة', genres: ['غموض', 'أكشن'], synopsis: 'انفجار في حديقة توكيو، وكونان يطارد القناص وسط الفوضى.' },
  { id: 'conan-movie-19', animeId: 'conan', title: 'Detective Conan Movie 19', titleAr: 'كونان: حديقة الجحيم الزهرية', poster: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.2, year: '2015', duration: '113 دقيقة', genres: ['غموض', 'أكشن'], synopsis: 'حديقة كاجورا تتحول إلى ساحة قتال، وكونان يواجه عدواً من الماضي.' },
  { id: 'conan-movie-20', animeId: 'conan', title: 'Detective Conan Movie 20', titleAr: 'كونان: الكابوس الأسود', poster: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.6, year: '2016', duration: '112 دقيقة', genres: ['غموض', 'أكشن'], synopsis: 'منظمة الرداء الأسود تظهر بقوة، وكونان يخوض أخطر معاركه ضدهم.' },
  { id: 'conan-movie-21', animeId: 'conan', title: 'Detective Conan Movie 21', titleAr: 'كونان: الحب الكارمي', poster: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.3, year: '2017', duration: '113 دقيقة', genres: ['غموض', 'أكشن'], synopsis: 'قضية قديمة لـ هايبارا تعود للظهور، وكونان يحميها من خطر محدق.' },
  { id: 'conan-movie-22', animeId: 'conan', title: 'Detective Conan Movie 22', titleAr: 'كونان: الجاسوس الصفري', poster: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.4, year: '2018', duration: '110 دقيقة', genres: ['غموض', 'أكشن'], synopsis: 'قمة دولية، جاسوس غامض، وكونان في قلب المؤامرة.' },
  { id: 'conan-movie-23', animeId: 'conan', title: 'Detective Conan Movie 23', titleAr: 'كونان: القبضة الزرقاء', poster: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.5, year: '2019', duration: '112 دقيقة', genres: ['غموض', 'أكشن'], synopsis: 'حادثة في سنغافورة تقود كونان في مغامرة دولية محفوفة بالمخاطر.' },
  { id: 'conan-movie-24', animeId: 'conan', title: 'Detective Conan Movie 24', titleAr: 'كونان: القرمزي النازف', poster: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.7, year: '2021', duration: '110 دقيقة', genres: ['غموض', 'أكشن'], synopsis: 'حادثة في منتجع جبلي تكشف شبكة تجسس دولية، وكونان يواجه عدواً خطيراً.' },
  { id: 'conan-movie-25', animeId: 'conan', title: 'Detective Conan Movie 25', titleAr: 'كونان: عروس هالوين', poster: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.6, year: '2022', duration: '111 دقيقة', genres: ['غموض', 'أكشن'], synopsis: 'حفل زفاف في هالوين يتحول إلى ساحة جريمة، وكونان يطارد القاتل المقنع.' },
  { id: 'conan-movie-26', animeId: 'conan', title: 'Detective Conan Movie 26', titleAr: 'كونان: الغواصة الحديدية', poster: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/7234253/pexels-photo-7234253.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.7, year: '2023', duration: '110 دقيقة', genres: ['غموض', 'أكشن', 'مغامرة'], synopsis: 'كونان وران يبحران في غواصة حديدية عملاقة عندما تقع جريمة قتل غامضة في أعماق المحيط.' },

  // ─── أفلام ون بيس (15 فيلماً) ───
  { id: 'onepiece-movie-1', animeId: 'onepiece', title: 'One Piece Movie 1', titleAr: 'ون بيس: الفيلم', poster: 'https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 7.5, year: '2000', duration: '51 دقيقة', genres: ['مغامرة', 'أكشن'], synopsis: 'لوفي وطاقمه يواجهون قرصاناً سرق كنزاً ثميناً من جزيرة صغيرة.' },
  { id: 'onepiece-movie-2', animeId: 'onepiece', title: 'One Piece Movie 2', titleAr: 'ون بيس: مغامرة جزيرة الساعة', poster: 'https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 7.6, year: '2001', duration: '55 دقيقة', genres: ['مغامرة', 'أكشن'], synopsis: 'الطاقم يصل إلى جزيرة تحكمها ساعة غامضة وقراصنة طموحة.' },
  { id: 'onepiece-movie-3', animeId: 'onepiece', title: 'One Piece Movie 3', titleAr: 'ون بيس: مملكة تشوبر على جزيرة الحيوانات', poster: 'https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 7.8, year: '2002', duration: '55 دقيقة', genres: ['مغامرة', 'كوميدي'], synopsis: 'تشوبر يقود معركة لتحرير جزيرة من حكم طاغية حيواني.' },
  { id: 'onepiece-movie-4', animeId: 'onepiece', title: 'One Piece Movie 4', titleAr: 'ون بيس: مغامرة ديد إند', poster: 'https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 7.9, year: '2003', duration: '95 دقيقة', genres: ['مغامرة', 'أكشن'], synopsis: 'سباق قراصنة بحري ينقلب إلى مغامرة خطيرة على جزيرة مليئة بالفخاخ.' },
  { id: 'onepiece-movie-5', animeId: 'onepiece', title: 'One Piece Movie 5', titleAr: 'ون بيس: لعنة السيف المقدس', poster: 'https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 7.7, year: '2004', duration: '95 دقيقة', genres: ['مغامرة', 'أكشن'], synopsis: 'زورو يختفي، والطاقم يكتشف سر سيف مقدس قديم.' },
  { id: 'onepiece-movie-6', animeId: 'onepiece', title: 'One Piece Movie 6', titleAr: 'ون بيس: بارون أوماتسوري والجزيرة السرية', poster: 'https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.0, year: '2005', duration: '92 دقيقة', genres: ['مغامرة', 'دراما'], synopsis: 'جزيرة احتفالية تخفي سراً مظلماً، والطاقم يتفرق في مواجهة الخطر.' },
  { id: 'onepiece-movie-7', animeId: 'onepiece', title: 'One Piece Movie 7', titleAr: 'ون بيس: جنرال الكاراتي العظيم', poster: 'https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 7.5, year: '2006', duration: '90 دقيقة', genres: ['مغامرة', 'أكشن'], synopsis: 'الطاقم يصل إلى جزيرة قديمة تخفي قوة الكاراتي الأسطورية.' },
  { id: 'onepiece-movie-8', animeId: 'onepiece', title: 'One Piece Movie 8', titleAr: 'ون بيس: صحراء الأعجوبة وقوات الحيوانات', poster: 'https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 7.8, year: '2007', duration: '90 دقيقة', genres: ['مغامرة', 'كوميدي'], synopsis: 'إعادة سرد قصة ألاباستا بجودة سينمائية عالية.' },
  { id: 'onepiece-movie-9', animeId: 'onepiece', title: 'One Piece Movie 9', titleAr: 'ون بيس: حلقة شيهلس الثلجية', poster: 'https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 7.9, year: '2008', duration: '113 دقيقة', genres: ['مغامرة', 'دراما'], synopsis: 'إعادة سرد قصة درام لوفي وأخيه في جزيرة ثلجية.' },
  { id: 'onepiece-movie-10', animeId: 'onepiece', title: 'One Piece Movie 10', titleAr: 'ون بيس: العالم القوي', poster: 'https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.5, year: '2009', duration: '113 دقيقة', genres: ['مغامرة', 'أكشن'], synopsis: 'شانكس يظهر، والطاقم يواجه عدواً من العصر القديم على جزيرة نائية.' },
  { id: 'onepiece-movie-11', animeId: 'onepiece', title: 'One Piece Movie 11', titleAr: 'ون بيس: سترو هات', poster: 'https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 7.6, year: '2011', duration: '113 دقيقة', genres: ['مغامرة', 'كوميدي'], synopsis: 'الطاقم يفقد ذاكرته ويجد نفسه في مدينة غريبة.' },
  { id: 'onepiece-movie-12', animeId: 'onepiece', title: 'One Piece Movie 12', titleAr: 'ون بيس: فيلم زد', poster: 'https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.7, year: '2012', duration: '107 دقيقة', genres: ['مغامرة', 'أكشن'], synopsis: 'الأدميرال زد يهدد العالم بأسلحة دمار شامل، ولوفي يواجهه.' },
  { id: 'onepiece-movie-13', animeId: 'onepiece', title: 'One Piece Movie 13', titleAr: 'ون بيس: غولد', poster: 'https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.3, year: '2016', duration: '120 دقيقة', genres: ['مغامرة', 'أكشن'], synopsis: 'الطاقم يصل إلى مدينة ترفيهية ضخمة يديرها رجل طموح بأسلوب خطير.' },
  { id: 'onepiece-movie-14', animeId: 'onepiece', title: 'One Piece Movie 14', titleAr: 'ون بيس: ستامبيد', poster: 'https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.4, year: '2019', duration: '101 دقيقة', genres: ['مغامرة', 'أكشن'], synopsis: 'مهرجان قراصنة عالمي، وكنز روجر الأسطوري في قلب السباق.' },
  { id: 'onepiece-movie-15', animeId: 'onepiece', malId: 491891, title: 'One Piece Film: Red', titleAr: 'ون بيس فيلم: أحمر', poster: 'https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.4, year: '2022', duration: '115 دقيقة', genres: ['مغامرة', 'أكشن', 'موسيقي'], synopsis: 'أوتا مغنية مشهورة بصوت خارق تكشف عن صلتها بـ شانكس. طاقم قبعة القش يجد نفسه في وسط مؤامرة كبرى.' },

  // ─── أفلام هجوم العمالقة (2 فيلمان) ───
  { id: 'aot-movie-1', animeId: 'aot', title: 'Attack on Titan: Crimson Bow and Arrow', titleAr: 'هجوم العمالقة: القوس والسهم القرمزي', poster: 'https://images.pexels.com/photos/2693208/pexels-photo-2693208.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/2693208/pexels-photo-2693208.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.5, year: '2014', duration: '118 دقيقة', genres: ['أكشن', 'دراما'], synopsis: 'تجميع لأحداث الموسم الأول بجودة سينمائية مع مشاهد إضافية.' },
  { id: 'aot-movie-2', animeId: 'aot', malId: 41437, title: 'Attack on Titan: The Final Season', titleAr: 'هجوم العمالقة: الموسم الأخير', poster: 'https://images.pexels.com/photos/2693208/pexels-photo-2693208.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/2693208/pexels-photo-2693208.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 9.1, year: '2023', duration: '150 دقيقة', genres: ['أكشن', 'دراما', 'خيال'], synopsis: 'المعركة الأخيرة بين إيرين وأصدقائه. مصير البشرية يتقرر في حرب طاحنة.' },

  // ─── أفلام قاتل الشياطين (3 أفلام) ───
  { id: 'demonslayer-movie-1', animeId: 'demonslayer', malId: 40456, title: 'Demon Slayer: Mugen Train', titleAr: 'قاتل الشياطين: قطار الأحلام', poster: 'https://images.pexels.com/photos/9987994/pexels-photo-9987994.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/9987994/pexels-photo-9987994.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.8, year: '2020', duration: '117 دقيقة', genres: ['أكشن', 'خارق', 'دراما'], synopsis: 'تانجيرو ورفاقه يصعدون قطار الأحلام للتحقيق في اختفاء أكثر من 40 شخصاً.' },
  { id: 'demonslayer-movie-2', animeId: 'demonslayer', title: 'Demon Slayer: To the Swordsmith Village', titleAr: 'قاتل الشياطين: إلى قرية صانعي السيوف', poster: 'https://images.pexels.com/photos/9987994/pexels-photo-9987994.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/9987994/pexels-photo-9987994.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.3, year: '2023', duration: '109 دقيقة', genres: ['أكشن', 'خارق'], synopsis: 'تانجيرو يرحل إلى قرية صانعي السيوف ويواجه شياطين كبار.' },
  { id: 'demonslayer-movie-3', animeId: 'demonslayer', title: 'Demon Slayer: Hashira Training', titleAr: 'قاتل الشياطين: تدريب الهاشيرا', poster: 'https://images.pexels.com/photos/9987994/pexels-photo-9987994.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/9987994/pexels-photo-9987994.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.1, year: '2024', duration: '103 دقيقة', genres: ['أكشن', 'خارق'], synopsis: 'تانجيرو يخضع لتدريب قاسٍ مع الهاشيرا استعداداً للمعركة الحاسمة.' },

  // ─── أفلام جوجوتسو كايسن (1 فيلم) ───
  { id: 'jjk-movie-1', animeId: 'jjk', malId: 48561, title: 'Jujutsu Kaisen 0', titleAr: 'جوجوتسو كايسن صفر', poster: 'https://images.pexels.com/photos/1634196/pexels-photo-1634196.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/1634196/pexels-photo-1634196.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.6, year: '2021', duration: '105 دقيقة', genres: ['أكشن', 'خارق', 'دراما'], synopsis: 'قصة يوتا أوكوتسو الطالب الذي تحول إلى وعاء لقوة ملعونة بعد موت صديقته.' },

  // ─── أفلام ناروتو (3 أفلام) ───
  { id: 'naruto-movie-1', animeId: 'naruto', title: 'Naruto Shippuden the Movie', titleAr: 'ناروتو شيبودن: الفيلم', poster: 'https://images.pexels.com/photos/2698929/pexels-photo-2698929.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/2698929/pexels-photo-2698929.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.0, year: '2007', duration: '95 دقيقة', genres: ['أكشن', 'مغامرة'], synopsis: 'ناروتو يحامي كاهنة من الموت بينما يطارد وحشاً أسطورياً.' },
  { id: 'naruto-movie-2', animeId: 'naruto', title: 'Naruto Shippuden Movie 2: Bonds', titleAr: 'ناروتو شيبودن: الروابط', poster: 'https://images.pexels.com/photos/2698929/pexels-photo-2698929.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/2698929/pexels-photo-2698929.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 7.8, year: '2008', duration: '93 دقيقة', genres: ['أكشن', 'دراما'], synopsis: 'ناروتو وساسكي يتحدان مؤقتاً ضد عدو مشترك يهدد القرية.' },
  { id: 'naruto-movie-3', animeId: 'naruto', title: 'Naruto Shippuden Movie 3: Will of Fire', titleAr: 'ناروتو شيبودن: إرادة النار', poster: 'https://images.pexels.com/photos/2698929/pexels-photo-2698929.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/2698929/pexels-photo-2698929.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 7.9, year: '2009', duration: '96 دقيقة', genres: ['أكشن', 'مغامرة'], synopsis: 'اختفاء كاكاشي يقود ناروتو في مهمة إنقاذ تكشف سراً قديماً.' },

  // ─── أفلام القناص (2 فيلمان) ───
  { id: 'hxh-movie-1', animeId: 'hxh', title: 'Hunter x Hunter: Phantom Rouge', titleAr: 'القناص: الشبح الأحمر', poster: 'https://images.pexels.com/photos/2698929/pexels-photo-2698929.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/2698929/pexels-photo-2698929.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.2, year: '2013', duration: '97 دقيقة', genres: ['أكشن', 'مغامرة'], synopsis: 'كورابيكا يفقد عينيه النينية، وغون وأصدقاؤه يبحثون عن اللص.' },
  { id: 'hxh-movie-2', animeId: 'hxh', title: 'Hunter x Hunter: The Last Mission', titleAr: 'القناص: المهمة الأخيرة', poster: 'https://images.pexels.com/photos/2698929/pexels-photo-2698929.jpeg?auto=compress&cs=tinysrgb&w=800', backdrop: 'https://images.pexels.com/photos/2698929/pexels-photo-2698929.jpeg?auto=compress&cs=tinysrgb&w=1600', rating: 8.0, year: '2013', duration: '97 دقيقة', genres: ['أكشن', 'مغامرة'], synopsis: 'مؤامرة قديمة في قمة الصيادين تهدد الجميع، وغون يواجه عدواً خطيراً.' },
];

// ═══════════════════════════════════════════════════════════════════
// ACCESSORS
// ═══════════════════════════════════════════════════════════════════

export function getAnimeById(id: string): Anime | undefined {
  return animeList.find((a) => a.id === id);
}

export function getMovieById(id: string): Movie | undefined {
  return movieList.find((m) => m.id === id);
}

export function getMoviesByAnimeId(animeId: string): Movie[] {
  return movieList.filter((m) => m.animeId === animeId);
}

export const allGenres = Array.from(
  new Set(animeList.flatMap((a) => a.genres))
).sort();
